redmine 4.2.1support
pangaeatech/redmine-stuff-to-do-plugin pull request #5
Opened 2021-10-09 01:57 UTC by Jiangshan00001

1 add redmine 4.2.1support
2 add doing now threshold_cnt in settings
3 fix an issue that someone could not see the top menu.

2021-10-09 01:58 UTC, Jiangshan00001 commented
#4

2021-10-11 20:21 UTC, mwaddell requested changes
@Jiangshan0001 Thank you for your PR, please see my comments.  Let me know if you have questions.

2021-10-11 20:21 UTC, mwaddell commented on app/models/stuff_to_do_mailer.rb
> -  default to: Setting.plugin_stuff_to_do_plugin['email_to'].split(',')
This change is unrelated to the 5 changes noted in the README.  It also makes this line inconsistent with the rest of this file where email addresses are split by comma.  Please remove this change

2021-10-11 20:21 UTC, mwaddell commented on app/models/stuff_to_do.rb
> +      .offset(Setting.plugin_stuff_to_do_plugin['threshold_cnt'])
When first deploying this branch and no value is set yet, both panels display identical lists since the setting is set to `Nil` instead of `5`

2021-10-11 20:21 UTC, mwaddell commented on app/views/stuff_to_do/index.html.erb
> +  <%= javascript_include_tag 'jquery-ui.min.js', plugin: 'stuff_to_do_plugin' %>
jquery-3.5.1-ui-1.12.1-ujs-5.2.4.5.js (which includes jquery ui) and jquery-migrate-3.3.2.min.js are already imported to the header of all pages by redmine 4.2.1, so including these same exact versions again again for the plugin pages is unnecessary.

2021-10-11 20:21 UTC, mwaddell commented on init.rb
> +  #})
This change will show the StD menu for all users regardless of whether they have permission or even if the StD plugin is enabled.  Please remove this change.

2021-10-11 20:21 UTC, mwaddell commented on assets/stylesheets/jquery-ui.css
> +/*! jQuery UI - v1.12.1 - 2021-10-10
This file is never actually used by StD

2021-10-11 20:21 UTC, mwaddell commented on assets/javascripts/stuff-to-do.js
> +
I'm getting the following client-side error when using this:

```console
stuff-to-do.js?1633982868:200 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at parseIssueId (stuff-to-do.js?1633982868:200)
    at s.fn.init.callback (stuff-to-do.js?1633982868:231)
    at HTMLLIElement.itemClick (jquery.contextMenu.js?1633982868:894)
    at HTMLDocument.dispatch (jquery-3.5.1.min.js?1633982868:2)
    at HTMLDocument.v.handle (jquery-3.5.1.min.js?1633982868:2)
```

Is there a conflict between the jquery.contextMenu plugin and Redmine 4.2.1's own custom contextMenu handler

2021-10-11 20:21 UTC, mwaddell commented on assets/stylesheets/jquery-ui.css
> +/*! jQuery UI - v1.12.1 - 2021-10-10
Actually NONE of the jquery UI css files are ever used

2021-10-12 10:36 UTC, Jiangshan00001 commented on app/models/stuff_to_do_mailer.rb
> -  default to: Setting.plugin_stuff_to_do_plugin['email_to'].split(',')
yes, you are right.
but just after the plugin  installed, the email address is empty. so split will fail.
i'll change the code anyway.

2021-10-12 10:36 UTC, Jiangshan00001 commented on app/models/stuff_to_do.rb
> +      .offset(Setting.plugin_stuff_to_do_plugin['threshold_cnt'])
i fix it.

2021-10-12 10:39 UTC, Jiangshan00001 commented on init.rb
> +  #})
maybe I do not know how to set the permission. 
I never get the top menu with the old code.

User.current.pref[:stuff_to_do_enabled] -- how to set?

2021-10-12 18:00 UTC, mwaddell commented
> 1 add redmine 4.2.1support

The current version already supports redmine 4.2.1 - I suspect your deployment has multiple plugins that are conflicting with one another.  When I deployed your branch in my test environment (see https://github.com/pangaeatech/redmine-stuff-to-do-plugin/issues/4#issuecomment-940416347), I got no bundler issues.

It is also not possible (currently) to upgrade jQuery since facebox.js and jquery.contextmenu rely on the older version.  I'll create a separate issue for addressing this.

> 2 add doing now threshold_cnt in settings

I would merge this new feature as a separate PR, the only thing it's missing is to better handle the case where the setting is still `Nil`

> 3 fix an issue that someone could not see the top menu.

Your fix enables the top menu for everyone even if they should not see it.  

Visibility for the StD plugin is managed by ROLE-based permissions.  Go into your administration page and give the roles that should have access to StD those permissions:

![image](https://user-images.githubusercontent.com/750244/137006217-3750f592-8c58-422e-81ef-4b59537b9005.png)

2021-10-12 18:29 UTC, mwaddell commented on config/locales/zh.yml
> +  permission_view_all_reportee_stuff_to_do: "See all issues of reportees with name"
Pulled out into a separate PR #7

2021-10-12 18:48 UTC, mwaddell commented on init.rb
> +  #})
Permissions are handled in `Administration` -> `Roles and Permissions` -- a new "Stuff To Do" section is added to the permissions for each role.

2021-10-12 18:48 UTC, mwaddell commented on app/models/stuff_to_do_mailer.rb
> -  default to: Setting.plugin_stuff_to_do_plugin['email_to'].split(',')
That's a valid point - a better way to fix this issue however, is:
`default to: (Setting.plugin_stuff_to_do_plugin['email_to'] || "").split(',')` 

(or using the ternary operator, etc)

2021-10-12 19:15 UTC, mwaddell commented
This PR contains too many distinct, partially-implemented things to be merged as-is:

Please do the following:
- Split out the threshold_cnt functionality into a separate PR where you can address the `Nil` issue
- Make this PR contain only your changes to the following files: 
  - app/models/stuff_to_do_mailer.rb (but addressing the `Nil` issue using `||` (or a ternary operator, etc))
  - app/views/stuff_to_do/_time_grid.html.erb
  - app/views/stuff_to_do/_panes.html.erb (add details about how to trigger this error for testing)

The rest of the changes from this PR will be addressed more completely in issue #6

2021-10-14 21:30 UTC, mwaddell commented
Replaced by PR #9

2021-10-14 21:30 UTC, closed without merging